### PR TITLE
Split core library from gradle plugin

### LINKED ISSUE #102: Separate core to another jar
@felipecsl needs the core part.
https://github.com/felipecsl/kales/pull/12

Separate the core, and release as 1.2.0.

* move core files
* rearrange docs

### PR DESCRIPTION
**Pull request by cromefire**
## What is this pull request for? Why do you create this pull request?
Fixes #102, also pretty much prerequisite for #155, alternative to #104 

## What is changed?
All the core stuff is now separated from the gradle plugin. I tried to maintain compatibility.

### CODE REVIEW

**Comment by cromefire** [comment]
I haven't really tested for compatibility yet and so I just hope that everything still works as intended, it seems good though.

The publishing is probably broken too (non existent for core).

**Comment by cromefire** [comment]
I also fixed some warnings, updated the code style to the new standard code style and some other minor stuff that just popped up.

**Comment by cromefire** [comment]
And I removed some files from git that don't belong there (all auto generated idea files)

**Comment by cromefire** [comment]
I also moved some new gradle stuff to `.kts` because it's just better at checking, completion and everything's kotlin anyways.

**Comment by cromefire** [comment]
Also the whole thing is more like a starting point. There's probably a lot to optimize and modularize afterwards (for example exposed references should be able to be excluded from core completely).

**Comment by KenjiOhtsuka** [comment]
@cromefire 
Looks good. let me see the detail :+1:

**Comment by KenjiOhtsuka** [comment]
@cromefire 
Excuse me, how could I execute test?
`./gradlew test` simply?

**Comment by cromefire** [comment]
Yeah I think so, it's been some time but I don't think I actually changed much of the functionality, other than to split it into 2 projects.

**Comment by KenjiOhtsuka** [comment]
I merged your branch to `feature/split` and executed the test as:

```
kenjiotsuka2@KenjinoMacBook-puro ~/project/harmonica
 % ./gradlew :core:test

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 811ms
3 actionable tasks: 3 up-to-date
```

but in my understanding, there are more tests. 🤔

image

**Comment by cromefire** [comment]
Fixed, gradle was missing the junit platform mode

**Comment by cromefire** [comment]
Let me just port the other gradle script too, so it's unified

**Comment by cromefire** [comment]
It's all kts now, have to check the core publishing though, but probably not today.

**Comment by KenjiOhtsuka** [comment]
@cromefire 
Thank you, but how can I test?

image
image

**Comment by KenjiOhtsuka** [comment]
@cromefire 
Sorry it looks working!
image

**Comment by KenjiOhtsuka** [comment]
@cromefire 
thanks! merged,

**Comment by KenjiOhtsuka** [comment]
@ashokgelal 

I merged this and split the core parts

**Comment by cromefire** [comment]
The one thing left to look out for, is if the publishing of the core library to your upstream maven repo is properly working, but think you still use the deprecated jCenter, so that might need an overhaul anyway.

**Pull request merged**
